#端口号
server:
  port: 8082

#mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://localhost:27017/mymongodb

  jpa:
    hibernate:
      ddl-auto: update  #第一次建表使用create，后面必须改为update，否则每次执行都会先删除表再建表

  redis:
    host: localhost
    port: 6379
    password: 123456
    #Redis数据库索引，默认是0 , 1表示第二个数据库，redis默认共有16个库 ，在命令行使用命令：select 1，切换到第二个数据库
    database: 1
    jedis:
      pool:
        max-active: 8  #最大连接数
        max-wait: -1   #连接阻塞时间，负值表示不限制
        max-idle: 8
    timeout: 2000  #连接超时时间
  http:
    multipart:
      max-file-size: 10
      max-request-size: 10

beetlsql:
  sqlPath: /sql
  basePackage: com.csxkaka.springbootstudy.beetl
beetl-beetlsql:
  dev: true

mybatis:
  type-aliases-package: com.csxkaka.springbootstudy.mybatis.entity
  mapper-locations: classpath:mybatis/*.xml


